name: CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test with Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2.6'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake

  lint:
    runs-on: ubuntu-latest
    name: Lint with Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2.6'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Lint code
        run: bundle exec rake standard
